### ISSUE TITLE
Can't change or disable focus (default highlighted field)

### ISSUE THREAD

**Issue by cylott** [BlueM/Pashua#11]
I've noticed that Pashua will assign focus (which UI element is highlighted and ready to accept input) to the first element of "text" type. Is there some way to disable focus or define it manually?

<img width="435" alt="screen shot 2018-08-16 at 4 36 23 pm" src="https://user-images.githubusercontent.com/42451226/44240379-a0262c00-a172-11e8-81b6-d915d6345dac.png">

**Comment by BlueM** [comment]
It depends on the system settings ➔ Keyboard ➔ Shortcuts. (At least I guess this is the English name, as I’m on a German system. See screenshot.) If you enable tabbing through all controls (not just text), the first control should be focused, regardless of type.

However, this is nothing Pashua itself controls, that’s just Cocoa. (At least according to a quick glance through the code. I might have written it such a long time ago, that I would not have necessarily remembered this.)

Defining the first focused element could/would be a side-effect of implementing #3.

![bildschirmfoto 2018-08-17 um 07 58 06](https://user-images.githubusercontent.com/1493457/44250236-dbb50a80-a1f3-11e8-8f83-5d43b140db16.png)
