### ISSUE TITLE
Broken links / disappeared destination pages in bluem.net

### ISSUE THREAD

**Issue by hmijail** [BlueM/Pashua#24]
The link to the Pashua homepage doesn't work; it just opens the "projects" page in bluem.net, which suggests GitHub back under the Pashua heading. So I could only find some docs for Pashua in [archive.org](https://web.archive.org/web/20210123052917/https://www.bluem.net/en/projects/pashua/).

Similarly, the link to your thoughts on Apple is broken, and I suspect that'd be a valuable thing to have.

**Comment by BlueM** [comment]
Two years ago or so I reduced my website to the absolute minimum – with the result that all application-specific pages are gone. But there was no significant content which isn’t also available here.

I was surprised to find that my thoughts on Apple are not on archive.org, so I just fetched them from a backup. So, just for the record, here it is (and keep in mind that it was written 4 years ago).

> On the evening of Oct 5, 2011 my partner and I were sitting in the Apollo Theater, Harlem, New York City, watching the famous “Amateur Night”. After the break, the host of the show returned on stage, informing the audience that Steve Jobs had passed away about an hour before. Sad, but hardly a surprise! After the end of the show, we spent the evening with another couple from Germany, who at that time happened to also be in NYC, in the Lenox Lounge (meanwhile gone, like Jobs), sipping cocktails and disussing what that could possibly mean for Apple. I recally very lively that I was convinced that Job’s death would not change too much. After all, he was extraordinary, but still an individual in that huge organization called Apple. I was so wrong!
> 
> I have used Macs for over 20 years. I bought my first Mac in May 1995 and in the years to follow, used MacOS 8 and 9 – despite its technical (albeit not usability) inferiority to Windows. When I first tried Mac OS X (in November 2001, version 10.1), I immediately realized that this is exactly what I wanted. I haven’t looked back to MacOS “Classic” ever since. In the years to come, Mac OS X was the operating system – not only for me, but for an increasing number of users, many of whom were developers. Stable, fresh UI, Unix under the hood, cool (and free!) development tools, safe, consistency everywhere (in shortcuts, UI patterns, looks, …). Plus new features such as Spotlight, Time Machine, the Safari browser (an extremely good browser in its early years). It was in this time when I started to develop applications for Mac OS X, primarily out of curiosity, later because some of the things I built attracted quite some audience.
> 
> This went on for a few years. If you used Mac OS X (later: OS X), you knew that you are using the right OS. And that combined with reliable, hassle-free and attractive hardware. Perfect.
>
> I don’t recall when I first thought things were going in the wrong direction. I guess it was even before Jobs’ death, but the things that possibly had worried me then were nothing against what the future was about to bring. With each major release of OS X (later: macOS), Apple introduced more bugs, without need removed some features and hardly added new features that were not related to iOS (which I would be absolutely fine with, if macOS still had the quality it had years ago). One might argue that the economic importance of iOS devices for Apple can’t be overestimated and that consequently, it is a wise decision to focus on iOS and iOS-related aspects in macOS. But then came 2017, and it became obvious that macOS does not suffer from a brain drain towards iOS, but it rather looked like there was hardly any brain at all, even in the iOS / mobile device department. The release of iOS 11 (which, by the way, made my iPhone significantly slower – thank you, Apple!) was followed by a whole bunch of updates and patches within less than two months. And then came Apple’s confession of throttling older device’s CPU, just before media started reporting on problems the flagship mobile phone, the iPhone X, had with receiving phone calls …
>
> In the same month as iOS 11, macOS 10.13 (“High Sierra”) was released, which introduced a new filesystem – which is probably not the best idea when it is not yet supported by some of the applications and tools that are shipped with the system. In late 2017, major security issues in macOS 10.13 were discovered – and a fix which Apple delivered broke filesharing, at least for some users. Only a few days after we learned that both iOS and macOS include a bug that causes misbehavior on at least some devices when used on or after December 2, 2017. (How shitty is that?) But this was even topped by a bug in macOS where you could just leave the password field empty in an authentication dialog and still authentication succeeded. Boy, what a mess! And the fact that Apple more often than not was reluctant to deliver security updates for older OS X versions didn’t win sympathies, either.
>
> I could go on and on, but I guess you get the point. Currently, at the beginning of 2018, I feel that something that I wouldn’t have considered possible could become reality: that I leave the Apple world. This is not in sight yet, but the mere consideration of switching says so much about what I as a long-term user (and developer of Mac software) feel about Apple right now …
> But while I not (yet) leave the Apple world as a user, I will leave it as a developer. Over the years, I wrote a whole bunch of Mac applications in my sparetime, some of which are used all over the world – despite the fact that most of them are rather specific and not very mass-compatible. In the last years, I have had little time to spend on maintaining these applications, but still: if you are committed to developing applications, you will find the time. Unfortunately, I am no longer committed – at least not to Mac applications. This has a number of reasons, but the decline of macOS is definitely one of them. Is it motivating to develop for a platform like the macOS of 2017? Make an educated guess …
>
> In the last maybe two years, I already declared a few applications as discontinued, such as Exif Untrasher and Taply. And although I hate to say so, others will follow in 2018. Most notably probably Pashua, an application for which I still get feedback and feature requests frequently – so this is sad, but realistically: I haven’t delivered a new version for over two years now, so the situation won’t get worse for Pashua, right? If you are a Pashua user and reading this, I can assure you that at least it will not simply vanish, but be open-sourced. Lots of people use it, and roughly 100% of Pashua users are developers of some kind, so if among them are a few Cocoa guys, this could even be the starting point for a brighter feature for Pashua, despite a codebase that is of mediocre quality and hasn’t had a major overhaul in its 15-year history.
>
> This text started with a misjudgement on my part. Maybe in a year or so I’ll read this text and find out that, again, I was wrong and that Apple got its act together. I would be happy!

**Comment by hmijail** [comment]
FWIW, the general explanation and FAQ in https://web.archive.org/web/20210314190422/https://www.bluem.net/pashua-docs-latest.html was very useful, and I didn't see anything like that in the repo itself.

I found now that in documentation/ there is a .xml file that seems to contain the source for that HTML. No idea if that gets turned into something more readable when Pashua is built.

**Comment by BlueM** [comment]
https://www.bluem.net/pashua-docs-latest.html ist still available, and this is the URL the `Documentation.webloc` file in Pashua’s DMG points at. But having the documentation versioned on GiHub would clearly be useful. I’ll look into it.
